name: zilliken
description: A restaurant menu app.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  firebase_core: ^0.5.0+1
  firebase_analytics: ^6.0.2
  firebase_auth: ^0.18.1+2
  cloud_firestore: ^0.14.1+3
  flutter_svg: ^0.19.1
  font_awesome_flutter: ^8.10.0
  flutter_statusbarcolor: ^0.2.3
  connectivity: ^2.0.0
  timelines: ^0.0.2+1
  google_sign_in: ^4.5.6
  curved_navigation_bar: ^0.3.7

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flappy_translator: ^1.5.0
  flutter_launcher_name: "^0.0.1"
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: "^0.8.1"
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/logo.jpg
    - assets/Zilliken.jpg
    - assets/menu.csv
    - assets/category.csv
    - assets/tea.jpg
    - assets/ginger tea.jpg
    - assets/cafe.jpeg
    - assets/expresso.jpg
    - assets/chocolat chaud.jpeg
    - assets/the marocain.jpg
    - assets/the-vert.jpg
    - assets/African tee.png
    - assets/eau plate.jpg
    - assets/eaupetillante.jpeg
    - assets/fanta.jpg
    - assets/passion.jpg
    - assets/viva.jpeg
    - assets/royal.jpg
    - assets/leffe.jpg
    - assets/heineken.jpg
    - assets/windhoek.png
    - assets/soupe de poulet legume.jpg
    - assets/soupe de legume.jpg
    - assets/soupe boeuf_legume.jpg
    - assets/soupe italienne.jpg
    - assets/omelette jambon fromage.jpg
    - assets/omelette_speciale.jpg
    - assets/omelette espagnole.jpg
    - assets/oeuf_sur_le_plat.jpg
    - assets/soupe_de_brocolis.jpg
    - assets/soupe de carotte.jpg
    - assets/sandwich jambon fromage.jpg
    - assets/croque monsieur.jpg
    - assets/fromagedechevre.jpeg
    - assets/tranche_de_baguette_au_pesto.jpg
    - assets/minibrochette_au_filet_de_boeuf.jpeg
    - assets/toastdecaptaine.jpeg
    - assets/minibrochetteaupoulet.jpeg
    - assets/salademixteaufromagedechevre.jpeg
    - assets/salademixte.jpeg
    - assets/salademixteaublancdepouletaveclardon.jpeg
    - assets/tranchedemozarellasurtomate.jpeg
    - assets/sangalabatonnetauxpoireaux.jpeg
    - assets/sangalaaucurry.jpeg
    - assets/sangalamenuiere.jpeg
    - assets/sangalagratineeauxepinards.jpeg
    - assets/sangalavinotheque.jpeg
    - assets/sangalaauvinblanc.jpeg
    - assets/sangalaalorange.jpeg
    - assets/sangalatapisse.jpeg
    - assets/sangalaencubeaulaitdecoco.jpeg
    - assets/sangalacremeauxchampignons.jpeg
    #- assets/crevettessauteesaubeurre.jpeg
    - assets/mukekeentier.jpeg
    - assets/croquettepoisson.jpeg
    - assets/calamar.jpeg
    - assets/gambasmoyen.jpeg
    - assets/tagliatelleavecchampignon.jpeg
    #- assets/tagliatelleaupoule
    - assets/tagliatelleemincedepouletauxchampignons.jpeg
    #- assets/tagliatelleemincedeboeuffromageblanc.jpeg
    - assets/steak de filet de boeuf.jpg
    - assets/steak hawaien.jpg
    - assets/steakvinoteque.jpeg
    - assets/steak avec gambas.jpg
    - assets/steakalexander.jpeg
    - assets/filet de boeuf au miel et sesame.jpg
    - assets/steak champignon creme.jpg
    - assets/filet facile.jpg
    - assets/filet espagnol.jpg
    - assets/gigot de chevre.jpg
    - assets/gigot d'agneau entier pour 2 personnes.jpg
    - assets/langue de boeuf cuit aux legumes.jpeg
    - assets/ragout de chevre.jpg
    - assets/gratin de boeuf aux pommes de terre et epinards.jpg
    - assets/ragout-de-chevre-aux-champigons-et-carottes.jpeg
    - assets/hamburger-frites.jpg
    - assets/mozzarelle cheeseburger-frites.jpg
    - assets/royal mozzarella cheeseburger-frite.jpg
    - assets/emince de blanc de poulet avec ses champignons noirs.jpg
    - assets/emince-de-blanc-de-poulet-au-curry.jpeg
    - assets/emince de blanc de poulet vinotheque.jpg
    - assets/blanc de poulet tapisse de ses legumes.jpeg
    - assets/quiche vegetarien avec salade.jpg
    - assets/quiche jambon avec salade.jpg
    - assets/saumon fume.jpg
    - assets/CAPITAINE FUMÉ(100g).jpeg
    - assets/legumes mixtes.jpg
    - assets/epinard.jpg
    - assets/frites.jpg
    - assets/petite salade.jpg
    - assets/couscous.jpg
    - assets/pommes de terre sautee aux legumes.jpg
    - assets/eau plate.jpg
    - assets/eaupetillante.jpeg
    - assets/fanta.jpg
    - assets/passion.jpg
    - assets/viva.jpeg
    - assets/royal.jpg
    - assets/leffe.jpg
    - assets/heineken.jpg
    - assets/américano.jpeg
    - assets/hakunamatata.jpeg
    - assets/greenpoison.jpeg
    - assets/tequilasunrise.jpeg
    - assets/specialgirl.jpeg
    - assets/punchpassion.jpeg
    - assets/appletini.jpeg
    - assets/longisland.jpeg
    - assets/moetetchandon.jpeg
    - assets/veuveclicquot.jpeg
    - assets/ST MILLIONEX.jpeg
    - assets/royalsalute.jpeg
    - assets/chivas18.jpeg
    - assets/chivas12.jpeg
    - assets/glenfidich12.jpeg
    - assets/courvoisier.jpeg
    - assets/martel.jpeg
    - assets/hennessy.jpeg
    - assets/remymartinvsop.jpeg
    - assets/gold.jpeg
    - assets/ELBLING  CLASSIC SEC.jpeg
    - assets/CUVEE MUSCHELKALK (PINOT ELBING)SEC.jpeg
    - assets/RIESLING SEC.jpeg
    - assets/RIESLING VENDAGE TARDIVEVIELLES VIGNES.jpeg
    - assets/DORNFELDER DEMI-SEC.jpeg
    - assets/CUVEE PINOTELBING EXTRA BRUT 1.jpeg
    - assets/ANANAS  ORANGE MANGUE.jpeg
    - assets/ANANAS  GINGEMBRE ORANGE.jpeg
    - assets/ORANGE CONCOMBRE ANANAS.jpeg
    - assets/MOCKTAIL (MOJITO SANS ALCOOL.jpeg
    - assets/hakunamatata.jpeg
    - assets/mojito.jpeg
    - assets/greenpoison.jpeg
    - assets/tequilasunrise.jpeg
    - assets/pinacolada.jpeg
    - assets/specialgirl.jpeg
    - assets/américano.jpeg
    - assets/BACARDI(Bacardi Jus de Citron Grenadine).jpeg
    - assets/appletini.jpeg
    - assets/GIN FIZZ(Gin Jus de citron Silop de sucre Soda).jpeg
    - assets/CUBA LIBRE(rum –coca cola –lime –soda).jpeg
    - assets/ZIZI COIN COIN(cointreau -jus de citron).jpeg
    - assets/NEGRONI(campari –martini-gin- soda).jpeg
    - assets/GIN TONIC(gin glacons tranche de citron tige romarin).jpeg
    - assets/LONG ISLAND(gin tequilla rum vodka cointreau coca jus de citron).jpeg
    - assets/VINOTHÈQUE(martini glaçons rouge).jpeg
    - assets/tequila.jpeg
    - assets/campari.jpeg
    - assets/baccardi.jpeg
    - assets/martini.jpeg
    - assets/vodka.jpeg
    - assets/gingordons.jpeg
    - assets/ginferdinands.jpeg
    - assets/cointreau.jpeg
    - assets/cremedecassis.jpeg
    - assets/grandmarnier.jpeg
    - assets/jackdaniels.jpeg
    - assets/henessy.jpeg
    - assets/chivas.jpeg
    - assets/goldlabel.jpeg
    - assets/martel.jpeg
    - assets/bombay.jpeg
    - assets/crepenature.jpeg
    - assets/crepenutella.jpeg
    - assets/crepenutellaavecbouledeglace.jpeg
    - assets/crepecitron.jpeg
    - assets/crepemiel.jpeg
    - assets/crepeultime.jpeg
    - assets/fruitsdesaison.jpeg
    - assets/saladedefruit.jpeg
    - assets/moelleuxauchocolat.jpeg
    - assets/bouledeglacevanille.jpeg
    - assets/brownieauchocolat.jpeg
    - assets/TAGLIATELLE ÉMINCÉ DE POULET AVEC CHAMPIGNON.jpeg
    - assets/TAGLIATELLE ÉMINCÉ DE BOEUF FROMAGE DE CHÈVRE.jpeg
    - assets/riz blancriz au curry.jpg
    - assets/pomme naturepureecroquettespommes de terre sautee aux oigons et lardon.jpg
    - assets/ST ISTEPLEX.jpeg
    - assets/ELBLING SEC 101.jpeg
    - assets/ELBLING FILIUS DEMI-SEC.JPEG
    - assets/CUVEE MUSCHELKALK (PINOT ELBING)SEC.jpeg
    - assets/RIESLING SEC.jpeg
    - assets/RIESLING  CRU CLASSEDEMI-SEC.jpeg
    - assets/PINOT BLANC SEC.jpeg
    - assets/PINOT AUXERROISSEC.jpeg
    - assets/SAUVIGNON BLANCSEC.jpeg
    - assets/SAUVIGNON BLANC FUMESEC.jpeg
    - assets/CHARDONNAYSEC.jpeg
    - assets/ELBLING ROSE SEC.jpg
    - assets/PINOT NOIRROSEDEMI-SEC.jpeg
    - assets/BLANC DE NOIRSEC.jpeg
    - assets/DORNFELDER SEC(101).jpeg
    - assets/PINOT NOIR SEC.jpeg
    - assets/PINOT NOIR SELECTION BARRIQUESEC.JPEG
    - assets/CUVEE JEAN BAPTISTESEC.jpeg
    - assets/RIESLING VIN MOUSSEUX  SEC 1.jpeg
    - assets/CAMPARI SPRITZ(Campari Vin Blanc Soda).jpeg
    - assets/GREEN POISON(Gin Jus d’orange Menthe).jpeg
    - assets/SPECIAL BOY(Martini Tonic Rum Crème De Cassis).jpeg
    - assets/PUNCH PASSION(Rum Fruito).jpeg
    - assets/CREVETTES SAUTÉES AU BEURRE ET À L'AIL.jpeg
    - assets/PINOT GRIS BARRIQUESEC.jpeg
    - assets/CUVEE PINOTELBING EXTRA BRUT 1.jpeg
    - assets/BOISSONS CHAUDES.jpg
    - assets/BOISSONS FRAICHES.jpg
    - assets/PETIT DÉJEUNER.jpg
    - assets/AMUSES BOUCHES.jpg
    - assets/SALADES.jpg
    - assets/LES POISSONS ET FRUITS DE MER.jpg
    - assets/PATES FRAICHES.jpg
    - assets/VIANDES.jpg
    - assets/POULETS.jpg
    - assets/ACCOMPAGNEMENTS.jpg
    - assets/AUTRES PLATS.jpg
    - assets/COCKTAIL.jpg
    - assets/AUTRES.jpg
    - assets/COCKTAILS SANS ALCOOL.jpg
    - assets/COCKTAIL.jpg
    - assets/DIGESTIFS.jpg
    - assets/DESSERTS.jpg
    - assets/VINS BLANCS (cépages originaires de la Moselle).jpg
    - assets/VINS BLANCS (cépages originaires de la Bourgogne).jpg
    - assets/VINS ROSÉS.jpg
    - assets/VINS ROUGES.jpg
    - assets/VINS MOUSSEUX.jpg
    - assets/tout.jpg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_launcher_name:
  name: "Zilliken"

flutter_native_splash:
  color: "#122F41"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpg"

flappy_translator:
  input_file_path: "strings.csv"
  output_dir: "lib"
  file_name: "i18n"
  class_name: "I18n"
  delimiter: ","
  start_index: 1
  depend_on_context: true
  use_single_quotes: false
  replace_no_break_spaces: false
  expose_get_string: false
  expose_loca_strings: false
  expose_locale_maps: false