// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: prefer_final_fields, public_member_api_docs, prefer_single_quotes, omit_local_variable_types, unnecessary_this

import 'dart:async';

import 'package:flutter/material.dart';

/// A  class generated by flappy_translator package containing localized strings
class I18n {
  String get appTitle => _getText("appTitle");

  String get menu => _getText("menu");

  String get orders => _getText("orders");

  String get error => _getText("error");

  String get loading => _getText("loading");

  String get taxCharge => _getText("taxCharge");

  String get sprkling => _getText("sprkling");

  String get orderKind => _getText("orderKind");

  String get bil => _getText("bil");

  String get ordPlace => _getText("ordPlace");

  String get instruction => _getText("instruction");

  String get restaurantOrder => _getText("restaurantOrder");

  String get total => _getText("total");

  String get tableNumber => _getText("tableNumber");

  String get address => _getText("address");

  String get orderDate => _getText("orderDate");

  String get item => _getText("item");

  String get items => _getText("items");

  String get fbu => _getText("fbu");

  String get roomNumber => _getText("roomNumber");

  String get pendingOrder => _getText("pendingOrder");

  String get confirmedOrder => _getText("confirmedOrder");

  String get orderPreparation => _getText("orderPreparation");

  String get orderServed => _getText("orderServed");

  String get and => _getText("and");

  String get moreItems => _getText("moreItems");

  String get order => _getText("order");

  String get orderInformation => _getText("orderInformation");

  String get billDetails => _getText("billDetails");

  String get ntable => _getText("ntable");

  String get livrdomicile => _getText("livrdomicile");

  String get gtotal => _getText("gtotal");

  String get addr => _getText("addr");

  String get fone => _getText("fone");

  String get requit => _getText("requit");

  String get cancelOrder => _getText("cancelOrder");

  String get orderDeleted => _getText("orderDeleted");

  String get pending => _getText("pending");

  String get confirmed => _getText("confirmed");

  String get preparing => _getText("preparing");

  String get served => _getText("served");

  String get number => _getText("number");

  String get updateStatus => _getText("updateStatus");

  String get vOrder => _getText("vOrder");

  String get addWhat => _getText("addWhat");

  String get category => _getText("category");

  String get addItem => _getText("addItem");

  String get categoryName => _getText("categoryName");

  String get itemPrice => _getText("itemPrice");

  String get itemName => _getText("itemName");

  String get noInternet => _getText("noInternet");

  String get login => _getText("login");

  String get logout => _getText("logout");

  String get accountDisabled => _getText("accountDisabled");

  String get grandTotal => _getText("grandTotal");

  String get orderStatus => _getText("orderStatus");

  String get loadData => _getText("loadData");

  String get orderPlaceholder => _getText("orderPlaceholder");

  String get operationFailed => _getText("operationFailed");

  String get operationSucceeded => _getText("operationSucceeded");

  String get pickImages => _getText("pickImages");

  String get cantSelect => _getText("cantSelect");

  String get photoChanged => _getText("photoChanged");

  String get yourphonenumber => _getText("yourphonenumber");

  String get requiredInput => _getText("requiredInput");

  String get signin => _getText("signin");

  String get smscode => _getText("smscode");

  String get confirm => _getText("confirm");

  String get yourname => _getText("yourname");

  String get signUp => _getText("signUp");

  String get createprofile => _getText("createprofile");

  String get createaccount => _getText("createaccount");

  static Map<String, String> _localizedValues;

  static Map<String, String> _enValues = {
    "appTitle": "Zilliken",
    "menu": "Menu",
    "orders": "Orders",
    "error": "Something went wrong",
    "loading": "Loading",
    "taxCharge": "Taxes & charges",
    "sprkling": "sparkiling water",
    "orderKind": "What kind of order is this?",
    "bil": "Bill",
    "ordPlace": "Place order",
    "instruction": "Do you have instructions?",
    "restaurantOrder": "Restaurant Order",
    "total": "Total",
    "tableNumber": "Table N.",
    "address": "Address",
    "orderDate": "Date",
    "item": "Item",
    "items": "Items",
    "fbu": "FBU",
    "roomNumber": "Room Number",
    "pendingOrder": "Order Pending",
    "confirmedOrder": "Order Confirmed",
    "orderPreparation": "Order Being Prepared",
    "orderServed": "Order Served",
    "and": "and",
    "moreItems": "More Items",
    "order": "Order",
    "orderInformation": "Informations",
    "billDetails": "Bill",
    "ntable": "Table Number",
    "livrdomicile": "Home delivery",
    "gtotal": "Grand Total",
    "addr": "Address",
    "fone": "Phone number",
    "requit": "Required",
    "cancelOrder": "Cancel Order",
    "orderDeleted": "Order Deleted",
    "pending": "Pending",
    "confirmed": "Confirmed",
    "preparing": "Preparing",
    "served": "Served",
    "number": "Number",
    "updateStatus": "Mettre à Jour Le Statut de la Commande",
    "vOrder": "View My Order",
    "addWhat": "What Do You Want to Add?",
    "category": "Category",
    "addItem": "Add",
    "categoryName": "Name of Categoy",
    "itemPrice": "Price of Item",
    "itemName": "Name of Item",
    "noInternet": "No Internet Connection",
    "login": "Log In",
    "logout": "Log Out",
    "accountDisabled": "This App Has Been Disabled",
    "grandTotal": "Grand Total",
    "orderStatus": "Order Status",
    "loadData": "Load Data",
    "orderPlaceholder": "Your Orders Will Appear Here",
    "operationFailed": "Operation Failed. Try Again Later",
    "operationSucceeded": "Operation Succeeded",
    "pickImages": "Pick An Image",
    "cantSelect": "You can't select any more",
    "photoChanged":
        "Profile Picture Changed. It may take some time to reflect in the app",
    "yourphonenumber": "Your Phone Number",
    "requiredInput": "*Required",
    "signin": "Sign In",
    "smscode": "SMS Code",
    "confirm": "Confirm",
    "yourname": "Enter Your Name",
    "signUp": "Sign UP",
    "createprofile": "Create Profile",
    "createaccount": "Create Account",
  };

  static Map<String, String> _frValues = {
    "appTitle": "Zilliken",
    "menu": "Menu",
    "orders": "Commandes",
    "error": "erreur survenue",
    "loading": "Chargement",
    "taxCharge": "Taxes et charges",
    "sprkling": "Eau petillante",
    "orderKind": "Quel genre de Commande est-ce?",
    "bil": "Facture",
    "ordPlace": "Passer la Commande",
    "instruction": "Avez-vous des instructions?",
    "restaurantOrder": "Commande de Restaurant",
    "total": "Total",
    "tableNumber": "N. table",
    "address": "Adresse",
    "orderDate": "Date",
    "item": "Article",
    "items": "Articles",
    "fbu": "FBU",
    "roomNumber": "Numero de Chambre",
    "pendingOrder": "Commande En Attente",
    "confirmedOrder": "Commande Confirmée",
    "orderPreparation": "Commande En Préparation",
    "orderServed": "Commande Servie",
    "and": "et",
    "moreItems": "Articles De Plus",
    "order": "Commande",
    "orderInformation": "Informations",
    "billDetails": "Facture",
    "ntable": "Numero de table",
    "livrdomicile": "Livraison a domicile",
    "gtotal": "Grand total",
    "addr": "Adresse",
    "fone": "Numero de telephone",
    "requit": "Requis",
    "cancelOrder": "Annuler Commande",
    "orderDeleted": "Commande Annulé",
    "pending": "En Attente",
    "confirmed": "Confirmé",
    "preparing": "En Préparation",
    "served": "Servie",
    "number": "Nombre",
    "updateStatus": "Update The Status Of The Order",
    "vOrder": "Voir Ma Commande",
    "addWhat": "Que Voulez-vous Ajouter?",
    "category": "Catégorie",
    "addItem": "Ajouter",
    "categoryName": "Nom de la Categorie",
    "itemPrice": "Prix de l'article",
    "itemName": "Nom de l'article",
    "noInternet": "Pas de Connexion Internet",
    "login": "Se Connecter",
    "logout": "Se Deconnecter",
    "accountDisabled": "Cette Application a été Désactivé",
    "grandTotal": "Total",
    "orderStatus": "Statut De La Commande",
    "loadData": "Charger Les Données",
    "orderPlaceholder": "Vos Commandes Apparaîtront Ici",
    "operationFailed": "L'opération a échoué. Reéssayez Plus Tard",
    "operationSucceeded": "L'Opération a réussie",
    "pickImages": "Choisir Une Image",
    "cantSelect": "Vous ne pouvez plus sélectionner",
    "photoChanged":
        "Image de profil changée. La réflexion dans l'application peut prendre un certain temps",
    "yourphonenumber": "Votre Numero de telephone",
    "requiredInput": "*Requis",
    "signin": "S'identifier",
    "smscode": "Code SMS",
    "confirm": "Confirmer",
    "yourname": "Entrez Votre Nom",
    "signUp": "Inscrivez-Vous",
    "createprofile": "créer un profil",
    "createaccount": "créer un compte",
  };

  static Map<String, Map<String, String>> _allValues = {
    "en": _enValues,
    "fr": _frValues,
  };

  I18n(Locale locale) {
    this._locale = locale;
    _localizedValues = null;
  }

  Locale _locale;

  static I18n of(BuildContext context) {
    return Localizations.of<I18n>(context, I18n);
  }

  String _getText(String key) {
    return _localizedValues[key] ?? '** $key not found';
  }

  Locale get currentLocale => _locale;

  String get currentLanguage => _locale.languageCode;

  static Future<I18n> load(Locale locale) async {
    final translations = I18n(locale);
    _localizedValues = _allValues[locale.toString()];
    return translations;
  }
}

class I18nDelegate extends LocalizationsDelegate<I18n> {
  const I18nDelegate();

  static final Set<Locale> supportedLocals = {
    Locale('en'),
    Locale('fr'),
  };

  @override
  bool isSupported(Locale locale) => supportedLocals.contains(locale);

  @override
  Future<I18n> load(Locale locale) => I18n.load(locale);

  @override
  bool shouldReload(I18nDelegate old) => false;
}
